/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectovino;

import javax.swing.JOptionPane;

/**
 *
 * @author RichiThe
 */
public class AgregarVino extends javax.swing.JFrame {
    private Array arr;
    /**
     * Creates new form AgregarVino
     */
    public AgregarVino() {
        arr = new Array();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodVino = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        cbnombreVino = new javax.swing.JComboBox<>();
        txtfieldCodVino = new javax.swing.JTextField();
        cbTipoVino = new javax.swing.JComboBox<>();
        CbTipoCepa = new javax.swing.JComboBox<>();
        cbSuelo = new javax.swing.JComboBox<>();
        cbBarrica = new javax.swing.JComboBox<>();
        lblNombreVino = new javax.swing.JLabel();
        lblTipoVino = new javax.swing.JLabel();
        lblTipoCepa = new javax.swing.JLabel();
        lblSuelo = new javax.swing.JLabel();
        lblBarrica = new javax.swing.JLabel();
        btnLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCodVino.setText("Codigo Vino");

        btnAgregar.setText("Agregar Vino");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        cbnombreVino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tinto", "Espumoso", "Blanco", "Rosado" }));

        cbTipoVino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacional", "Internacional" }));

        CbTipoCepa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cavernet Souvignon", "Merlot" }));

        cbSuelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arenoso", "Arcilloso" }));

        cbBarrica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roble", "Abeto" }));

        lblNombreVino.setText("Nombre Vino");

        lblTipoVino.setText("Tipo Vino");

        lblTipoCepa.setText("Tipo Cepa");

        lblSuelo.setText("Tipo Suelo");

        lblBarrica.setText("Tipo Barrica");

        btnLista.setText("Lista Vino");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodVino)
                            .addComponent(lblNombreVino)
                            .addComponent(lblTipoVino)
                            .addComponent(lblTipoCepa)
                            .addComponent(lblSuelo)
                            .addComponent(lblBarrica))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbnombreVino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtfieldCodVino)
                                    .addComponent(cbTipoVino, 0, 123, Short.MAX_VALUE))
                                .addGap(122, 122, 122))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbBarrica, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CbTipoCepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodVino)
                            .addComponent(txtfieldCodVino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbnombreVino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNombreVino))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoVino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoVino))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbTipoCepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoCepa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuelo)
                    .addComponent(cbSuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarrica, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBarrica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnLista))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(!txtfieldCodVino.getText().equals(""))
        {    
         Vino vins = new Vino();
         Cepa cep =  new Cepa();
         Barrica bar = new Barrica();
         Suelo sue = new Suelo();
         String c = txtfieldCodVino.getText();
         int cod = Integer.parseInt(c);
         cep.setTipoCepa(CbTipoCepa.getSelectedItem().toString());
         bar.setTipoBarrica(cbBarrica.getSelectedItem().toString());
         sue.setTipoSuelo(cbSuelo.getSelectedItem().toString());
         vins.setCep(cep);
         vins.setCodVino(cod);
         vins.setNombreVino(cbnombreVino.getSelectedItem().toString());
         vins.setTipoVino(cbTipoVino.getSelectedItem().toString());
         vins.setBar(bar);
         vins.setSue(sue);
        // Array arr = new Array();
        
         arr.agregarVino(vins);
         JOptionPane.showMessageDialog(null, "Vino Agregado exitosamente");
        }
        else
        {
          JOptionPane.showMessageDialog(null, "Error no hay codigo");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        ListaVino list = new ListaVino();
        list.Datos(this.arr.listaVino());
    }//GEN-LAST:event_btnListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarVino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarVino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarVino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarVino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarVino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbTipoCepa;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLista;
    private javax.swing.JComboBox<String> cbBarrica;
    private javax.swing.JComboBox<String> cbSuelo;
    private javax.swing.JComboBox<String> cbTipoVino;
    private javax.swing.JComboBox<String> cbnombreVino;
    private javax.swing.JLabel lblBarrica;
    private javax.swing.JLabel lblCodVino;
    private javax.swing.JLabel lblNombreVino;
    private javax.swing.JLabel lblSuelo;
    private javax.swing.JLabel lblTipoCepa;
    private javax.swing.JLabel lblTipoVino;
    private javax.swing.JTextField txtfieldCodVino;
    // End of variables declaration//GEN-END:variables
}
